pipeline {
  agent {
    kubernetes {
      label 'jenkins_job_builder'
      yamlFile 'jenkins-job-builder/KubernetesPod.yaml'
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
        }
        container('busybox') {
          sh '/bin/busybox'
        }
      }
    }
  }
}
