pipeline {
    triggers {
      pollSCM('* * * * *')
    }
    agent {
        kubernetes {
            label 'jenkins_job_builder'
            yaml 'jenkins-job-builder/pod.yml'
             }
          }
    stages {
        stage('Example') {
            steps {
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
    }
}
