---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-job-builder
  labels:
    some-label: jenkins-job-builder
spec:
  containers:
    - name: jenkins-job-builder
      image: osmman/jenkins-job-builder:latest
      command:
        - cat
      tty: true
